# Generated by Django 5.1.3 on 2024-11-27 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique_user_post_bookmark',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('owner', 'post'), name='unique_owner_post_bookmark'),
        ),
    ]
