# Generated by Django 3.2.25 on 2025-02-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Food event', 'Food event'), ('Drinks event', 'Drinks event'), ('Sommerfestival', 'Sommerfestival'), ('Winterfestival', 'Winterfestival'), ('Exhibition', 'Exhibition'), ('Other', 'Other')], default='Food event', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
    ]
