# Generated by Django 3.2.25 on 2025-02-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='test_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
