# Generated by Django 3.2.25 on 2025-02-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_eventattendance_test_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together=set(),
        ),
    ]
