# Generated by Django 3.2.25 on 2025-02-28 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0004_alter_eventattendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together={('user', 'event')},
        ),
    ]
